authors:
  mike-branson:
    name: Mike Branson
    description: Application Enablement Director
    avatar: https://www.gravatar.com/avatar/gravatarmysteryman
  paul-gerver:
    name: Paul Gerver
    description: Streams Software Engineer
    avatar: https://www.gravatar.com/avatar/0b0bd58f015aa5e93dd8a66e844c350cfb4e44f4eb2916cb3f107c2cb9ce16bf